services:
  greenlight:
    build:
      context: .
    image: denpeshkov/greenlight
    container_name: greenlight
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:16.1-alpine"
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data

volumes:
  pg-data: