name: Go

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build, lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21
          cache: false # managed by golangci-lint
      
      - name: Download Dependencies
        run: go mod download -x

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: go test -v -race ./...
    
